//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API_RailWay.App_LocalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string button_title_view {
            get {
                return ResourceManager.GetString("button_title_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите период времени для формирования отчета :.
        /// </summary>
        public static string dts_сhoose_period {
            get {
                return ResourceManager.GetString("dts_сhoose_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти на станцию.
        /// </summary>
        public static string home_index_link_station {
            get {
                return ResourceManager.GetString("home_index_link_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние парка.
        /// </summary>
        public static string home_index_park_state {
            get {
                return ResourceManager.GetString("home_index_park_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string Layout_rw_link_admins {
            get {
                return ResourceManager.GetString("Layout_rw_link_admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Layout_rw_link_contacs {
            get {
                return ResourceManager.GetString("Layout_rw_link_contacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкции.
        /// </summary>
        public static string Layout_rw_link_instructions {
            get {
                return ResourceManager.GetString("Layout_rw_link_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string Layout_rw_link_reports {
            get {
                return ResourceManager.GetString("Layout_rw_link_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование web-приложения.
        /// </summary>
        public static string Layout_rw_title_admins {
            get {
                return ResourceManager.GetString("Layout_rw_title_admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои контакты ниже!.
        /// </summary>
        public static string Layout_rw_title_contacs {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Административная поддержка (предоставление доступа, настройка web-приложения).
        /// </summary>
        public static string Layout_rw_title_contacs_admin {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сидоренко Евгений.
        /// </summary>
        public static string Layout_rw_title_contacs_admin_name {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_admin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель проекта.
        /// </summary>
        public static string Layout_rw_title_contacs_admin_post {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_admin_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая поддержка (Ошибки, администрирование базы данных, разработка web-приложения).
        /// </summary>
        public static string Layout_rw_title_contacs_deverl {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_deverl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левченко Эдуард.
        /// </summary>
        public static string Layout_rw_title_contacs_deverl_name {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_deverl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальник отдела промышленных систем автоматизации ДАТП.
        /// </summary>
        public static string Layout_rw_title_contacs_deverl_post {
            get {
                return ResourceManager.GetString("Layout_rw_title_contacs_deverl_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкции.
        /// </summary>
        public static string Layout_rw_title_instructions {
            get {
                return ResourceManager.GetString("Layout_rw_title_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-сайт ДАТП.
        /// </summary>
        public static string Layout_rw_web_dpa {
            get {
                return ResourceManager.GetString("Layout_rw_web_dpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string link_add {
            get {
                return ResourceManager.GetString("link_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string link_cancel {
            get {
                return ResourceManager.GetString("link_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string link_create {
            get {
                return ResourceManager.GetString("link_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string link_delete {
            get {
                return ResourceManager.GetString("link_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Править.
        /// </summary>
        public static string link_edit {
            get {
                return ResourceManager.GetString("link_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти ».
        /// </summary>
        public static string link_goto {
            get {
                return ResourceManager.GetString("link_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить.
        /// </summary>
        public static string link_run {
            get {
                return ResourceManager.GetString("link_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы обрабатываем ваш запрос....
        /// </summary>
        public static string lock_text {
            get {
                return ResourceManager.GetString("lock_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RailWay - web приложение учета подвижного состава ПАО &quot;АрселорМиттал Кривой Рог.
        /// </summary>
        public static string rw_caption {
            get {
                return ResourceManager.GetString("rw_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать ».
        /// </summary>
        public static string rw_report_link {
            get {
                return ResourceManager.GetString("rw_report_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КИС.
        /// </summary>
        public static string rw_title_report_kis {
            get {
                return ResourceManager.GetString("rw_title_report_kis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным информационной системой КИС. Информация о перемещении подвижного состава на территории АМКР..
        /// </summary>
        public static string rw_title_report_kis_desc {
            get {
                return ResourceManager.GetString("rw_title_report_kis_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО «Металлургтранс».
        /// </summary>
        public static string rw_title_report_mt {
            get {
                return ResourceManager.GetString("rw_title_report_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным компанией ООО «Металлургтранс». Информация о вагонах находящихся на станциях УЗ Кривого Рога направляющихся на станции АМКР..
        /// </summary>
        public static string rw_title_report_mt_desc {
            get {
                return ResourceManager.GetString("rw_title_report_mt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RailWay.
        /// </summary>
        public static string rw_title_report_rw {
            get {
                return ResourceManager.GetString("rw_title_report_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным информационной системой RailWay. Информация о перемещении подвижного состава на территории АМКР..
        /// </summary>
        public static string rw_title_report_rw_desc {
            get {
                return ResourceManager.GetString("rw_title_report_rw_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите период:.
        /// </summary>
        public static string select_date_range_title {
            get {
                return ResourceManager.GetString("select_date_range_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль:.
        /// </summary>
        public static string select_eventid_title {
            get {
                return ResourceManager.GetString("select_eventid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип лога.
        /// </summary>
        public static string select_level_title {
            get {
                return ResourceManager.GetString("select_level_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис:.
        /// </summary>
        public static string select_service_title {
            get {
                return ResourceManager.GetString("select_service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип отчета.
        /// </summary>
        public static string select_type_report_title {
            get {
                return ResourceManager.GetString("select_type_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопределенно.
        /// </summary>
        public static string side_empty {
            get {
                return ResourceManager.GetString("side_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Четная.
        /// </summary>
        public static string side_even {
            get {
                return ResourceManager.GetString("side_even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нечетная.
        /// </summary>
        public static string side_odd {
            get {
                return ResourceManager.GetString("side_odd", resourceCulture);
            }
        }
    }
}
