//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KISResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KISResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_RailWay.App_LocalResources.KISResource", typeof(KISResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалена.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string global {
            get {
                return ResourceManager.GetString("global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным информационной системой КИС. Информация о перемещении подвижного состава на территории АМКР..
        /// </summary>
        public static string index_description {
            get {
                return ResourceManager.GetString("index_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование данных из КИС прибытие составов с УЗ.
        /// </summary>
        public static string index_report_arrival_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие с УЗ.
        /// </summary>
        public static string index_report_arrival_title {
            get {
                return ResourceManager.GetString("index_report_arrival_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование данных из КИС с внутренних станций по прибытию.
        /// </summary>
        public static string index_report_input_desc {
            get {
                return ResourceManager.GetString("index_report_input_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие по АМКР.
        /// </summary>
        public static string index_report_input_title {
            get {
                return ResourceManager.GetString("index_report_input_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование данных из КИС с внутренних станций по отправке.
        /// </summary>
        public static string index_report_output_desc {
            get {
                return ResourceManager.GetString("index_report_output_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка по АМКР.
        /// </summary>
        public static string index_report_output_title {
            get {
                return ResourceManager.GetString("index_report_output_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КИС.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлена.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос выполнен\закрыт.
        /// </summary>
        public static string kis_report_field_arrival_close {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. вагонов. (Prom.Vagon).
        /// </summary>
        public static string kis_report_field_arrival_count_wag {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_count_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторона.
        /// </summary>
        public static string kis_report_field_arrival_napr {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_napr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на таб. Prom.NatHist, кол.вагонов (перенесено).
        /// </summary>
        public static string kis_report_field_arrival_nathist {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_nathist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. вагонов. (Prom.NatHist).
        /// </summary>
        public static string kis_report_field_arrival_nh_count_wag {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_nh_count_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесено (Prom.NatHist).
        /// </summary>
        public static string kis_report_field_arrival_nh_set_count_wag {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_nh_set_count_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесено (Prom.Vagon).
        /// </summary>
        public static string kis_report_field_arrival_set_count_wag {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_set_count_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыл на станцию.
        /// </summary>
        public static string kis_report_field_arrival_station {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на таб. Prom.Vagon, кол.вагонов (перенесено).
        /// </summary>
        public static string kis_report_field_arrival_wagons {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        public static string kis_report_field_arrival_way {
            get {
                return ResourceManager.GetString("kis_report_field_arrival_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        public static string kis_report_field_car {
            get {
                return ResourceManager.GetString("kis_report_field_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесен.
        /// </summary>
        public static string kis_report_field_car_set {
            get {
                return ResourceManager.GetString("kis_report_field_car_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлен.
        /// </summary>
        public static string kis_report_field_car_upd {
            get {
                return ResourceManager.GetString("kis_report_field_car_upd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время.
        /// </summary>
        public static string kis_report_field_datetime {
            get {
                return ResourceManager.GetString("kis_report_field_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Натурки.
        /// </summary>
        public static string kis_report_field_natur {
            get {
                return ResourceManager.GetString("kis_report_field_natur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус строки.
        /// </summary>
        public static string kis_report_field_status {
            get {
                return ResourceManager.GetString("kis_report_field_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос.
        /// </summary>
        public static string kis_trnsfer_arrival_report_home {
            get {
                return ResourceManager.GetString("kis_trnsfer_arrival_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование данных из КИС прибытие составов с УЗ Кривого Рога.
        /// </summary>
        public static string kis_trnsfer_arrival_report_title {
            get {
                return ResourceManager.GetString("kis_trnsfer_arrival_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос данных по прибытию с УЗ.
        /// </summary>
        public static string link_kis_arrival_control {
            get {
                return ResourceManager.GetString("link_kis_arrival_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос данных по прибытию.
        /// </summary>
        public static string link_kis_input_control {
            get {
                return ResourceManager.GetString("link_kis_input_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила переноса по прибытию.
        /// </summary>
        public static string link_kis_input_rules {
            get {
                return ResourceManager.GetString("link_kis_input_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос данных по отправке.
        /// </summary>
        public static string link_kis_output_control {
            get {
                return ResourceManager.GetString("link_kis_output_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила переноса по отправке.
        /// </summary>
        public static string link_kis_output_rules {
            get {
                return ResourceManager.GetString("link_kis_output_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_del_input.
        /// </summary>
        public static string no_del_input {
            get {
                return ResourceManager.GetString("no_del_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_del_output.
        /// </summary>
        public static string no_del_output {
            get {
                return ResourceManager.GetString("no_del_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Годность?.
        /// </summary>
        public static string no_godn {
            get {
                return ResourceManager.GetString("no_godn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз?.
        /// </summary>
        public static string no_gruz {
            get {
                return ResourceManager.GetString("no_gruz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_owner.
        /// </summary>
        public static string no_owner {
            get {
                return ResourceManager.GetString("no_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_owner_country.
        /// </summary>
        public static string no_owner_country {
            get {
                return ResourceManager.GetString("no_owner_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_shop.
        /// </summary>
        public static string no_shop {
            get {
                return ResourceManager.GetString("no_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_station_nazn.
        /// </summary>
        public static string no_station_nazn {
            get {
                return ResourceManager.GetString("no_station_nazn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция?.
        /// </summary>
        public static string no_stations {
            get {
                return ResourceManager.GetString("no_stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_tupik.
        /// </summary>
        public static string no_tupik {
            get {
                return ResourceManager.GetString("no_tupik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_wagon_is_list.
        /// </summary>
        public static string no_wagon_is_list {
            get {
                return ResourceManager.GetString("no_wagon_is_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NatHist-нет вагона.
        /// </summary>
        public static string no_wagon_is_nathist {
            get {
                return ResourceManager.GetString("no_wagon_is_nathist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no_wagons.
        /// </summary>
        public static string no_wagons {
            get {
                return ResourceManager.GetString("no_wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь?.
        /// </summary>
        public static string no_ways {
            get {
                return ResourceManager.GetString("no_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set_table_arrival_sostav.
        /// </summary>
        public static string set_table_arrival_sostav {
            get {
                return ResourceManager.GetString("set_table_arrival_sostav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменена.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
