//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_RailWay.App_LocalResources.LogResource", typeof(LogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время.
        /// </summary>
        public static string log_datetime {
            get {
                return ResourceManager.GetString("log_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string log_errors_datetime_user_message {
            get {
                return ResourceManager.GetString("log_errors_datetime_user_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль.
        /// </summary>
        public static string log_eventID {
            get {
                return ResourceManager.GetString("log_eventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие.
        /// </summary>
        public static string log_events_event {
            get {
                return ResourceManager.GetString("log_events_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус выполнения.
        /// </summary>
        public static string log_events_status {
            get {
                return ResourceManager.GetString("log_events_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код выполнения.
        /// </summary>
        public static string log_services_code_return {
            get {
                return ResourceManager.GetString("log_services_code_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время выполнения.
        /// </summary>
        public static string log_services_current {
            get {
                return ResourceManager.GetString("log_services_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время выполнения (мсек.).
        /// </summary>
        public static string log_services_duration {
            get {
                return ResourceManager.GetString("log_services_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последнее выполнение.
        /// </summary>
        public static string log_services_execution {
            get {
                return ResourceManager.GetString("log_services_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. (мсек).
        /// </summary>
        public static string log_services_max {
            get {
                return ResourceManager.GetString("log_services_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мин. (мсек).
        /// </summary>
        public static string log_services_min {
            get {
                return ResourceManager.GetString("log_services_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис.
        /// </summary>
        public static string log_services_name {
            get {
                return ResourceManager.GetString("log_services_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис.
        /// </summary>
        public static string log_services_report_home {
            get {
                return ResourceManager.GetString("log_services_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет о работе сервисов RailWay.
        /// </summary>
        public static string log_services_report_title {
            get {
                return ResourceManager.GetString("log_services_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запущен.
        /// </summary>
        public static string log_services_start {
            get {
                return ResourceManager.GetString("log_services_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки.
        /// </summary>
        public static string log_tab_title_errors {
            get {
                return ResourceManager.GetString("log_tab_title_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        public static string log_tab_title_event {
            get {
                return ResourceManager.GetString("log_tab_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отработка.
        /// </summary>
        public static string log_tab_title_services {
            get {
                return ResourceManager.GetString("log_tab_title_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string log_tab_title_setup {
            get {
                return ResourceManager.GetString("log_tab_title_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание настройки.
        /// </summary>
        public static string setting_description {
            get {
                return ResourceManager.GetString("setting_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key.
        /// </summary>
        public static string setting_key {
            get {
                return ResourceManager.GetString("setting_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string setting_type {
            get {
                return ResourceManager.GetString("setting_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string setting_value {
            get {
                return ResourceManager.GetString("setting_value", resourceCulture);
            }
        }
    }
}
