//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MTResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MTResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_RailWay.App_LocalResources.MTResource", typeof(MTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным компанией ООО «Металлургтранс». Информация о вагонах находящихся на станциях УЗ Кривого Рога направляющихся на станции АМКР..
        /// </summary>
        public static string index_description {
            get {
                return ResourceManager.GetString("index_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_cargo_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_cargo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы.
        /// </summary>
        public static string index_report_approaches_cargo_title {
            get {
                return ResourceManager.GetString("index_report_approaches_cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузом АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_cars_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_cars_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string index_report_approaches_cars_title {
            get {
                return ResourceManager.GetString("index_report_approaches_cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на подходах с грузом АМКР, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы с грузами АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_sostav_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_sostav_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string index_report_approaches_sostav_title {
            get {
                return ResourceManager.GetString("index_report_approaches_sostav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на подходах.
        /// </summary>
        public static string index_report_approaches_title {
            get {
                return ResourceManager.GetString("index_report_approaches_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_cargo_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_cargo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы.
        /// </summary>
        public static string index_report_arrival_cargo_title {
            get {
                return ResourceManager.GetString("index_report_arrival_cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузом АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_cars_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_cars_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string index_report_arrival_cars_title {
            get {
                return ResourceManager.GetString("index_report_arrival_cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на станциях УЗ Кривого Рога с грузом АМКР, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы с грузами АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_sostav_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_sostav_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string index_report_arrival_sostav_title {
            get {
                return ResourceManager.GetString("index_report_arrival_sostav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие вагонов.
        /// </summary>
        public static string index_report_arrival_title {
            get {
                return ResourceManager.GetString("index_report_arrival_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Положение вагонов собственного парка, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_cars_amkr_desc {
            get {
                return ResourceManager.GetString("index_report_cars_amkr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны АМКР.
        /// </summary>
        public static string index_report_cars_amkr_title {
            get {
                return ResourceManager.GetString("index_report_cars_amkr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО Металлургтранс.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string link_goto_mt {
            get {
                return ResourceManager.GetString("link_goto_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string mt_arrival_sostsv_report_home {
            get {
                return ResourceManager.GetString("mt_arrival_sostsv_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы на УЗ Кривого Рога.
        /// </summary>
        public static string mt_arrival_sostsv_report_title {
            get {
                return ResourceManager.GetString("mt_arrival_sostsv_report_title", resourceCulture);
            }
        }
    }
}
