//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MTResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MTResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_RailWay.App_LocalResources.MTResource", typeof(MTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все вагоны.
        /// </summary>
        public static string all_cars {
            get {
                return ResourceManager.GetString("all_cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны для АМКР.
        /// </summary>
        public static string amkr_cars {
            get {
                return ResourceManager.GetString("amkr_cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны для АМКР, принятые.
        /// </summary>
        public static string amkr_cars_arival {
            get {
                return ResourceManager.GetString("amkr_cars_arival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны для АМКР, не принятые.
        /// </summary>
        public static string amkr_cars_no_arival {
            get {
                return ResourceManager.GetString("amkr_cars_no_arival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт по ТСП.
        /// </summary>
        public static string close_car {
            get {
                return ResourceManager.GetString("close_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт по грузу.
        /// </summary>
        public static string close_different_cargo {
            get {
                return ResourceManager.GetString("close_different_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт вручную.
        /// </summary>
        public static string close_manual {
            get {
                return ResourceManager.GetString("close_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт по изменению маршрута.
        /// </summary>
        public static string close_new_route {
            get {
                return ResourceManager.GetString("close_new_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт по времени.
        /// </summary>
        public static string close_timeout {
            get {
                return ResourceManager.GetString("close_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие.
        /// </summary>
        public static string coming {
            get {
                return ResourceManager.GetString("coming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным компанией ООО «Металлургтранс». Информация о вагонах находящихся на станциях УЗ Кривого Рога направляющихся на станции АМКР..
        /// </summary>
        public static string index_description {
            get {
                return ResourceManager.GetString("index_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_cargo_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_cargo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы.
        /// </summary>
        public static string index_report_approaches_cargo_title {
            get {
                return ResourceManager.GetString("index_report_approaches_cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузом АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_cars_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_cars_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string index_report_approaches_cars_title {
            get {
                return ResourceManager.GetString("index_report_approaches_cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на подходах с грузом АМКР, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы с грузами АМКР, на подходах к станциям УЗ Кривой Рог, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_approaches_sostav_desc {
            get {
                return ResourceManager.GetString("index_report_approaches_sostav_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string index_report_approaches_sostav_title {
            get {
                return ResourceManager.GetString("index_report_approaches_sostav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на подходах.
        /// </summary>
        public static string index_report_approaches_title {
            get {
                return ResourceManager.GetString("index_report_approaches_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_cargo_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_cargo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы.
        /// </summary>
        public static string index_report_arrival_cargo_title {
            get {
                return ResourceManager.GetString("index_report_arrival_cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузом АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_cars_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_cars_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string index_report_arrival_cars_title {
            get {
                return ResourceManager.GetString("index_report_arrival_cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны на станциях УЗ Кривого Рога с грузом АМКР, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы с грузами АМКР, на станциях УЗ Кривого Рога, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_arrival_sostav_desc {
            get {
                return ResourceManager.GetString("index_report_arrival_sostav_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string index_report_arrival_sostav_title {
            get {
                return ResourceManager.GetString("index_report_arrival_sostav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие вагонов.
        /// </summary>
        public static string index_report_arrival_title {
            get {
                return ResourceManager.GetString("index_report_arrival_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Положение вагонов собственного парка, по данным ООО «МеталлургТранс».
        /// </summary>
        public static string index_report_cars_amkr_desc {
            get {
                return ResourceManager.GetString("index_report_cars_amkr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны АМКР.
        /// </summary>
        public static string index_report_cars_amkr_title {
            get {
                return ResourceManager.GetString("index_report_cars_amkr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция.
        /// </summary>
        public static string index_report_field_operation {
            get {
                return ResourceManager.GetString("index_report_field_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО Металлургтранс.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На подходах:.
        /// </summary>
        public static string link_approaches {
            get {
                return ResourceManager.GetString("link_approaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По прибытию:.
        /// </summary>
        public static string link_arrival {
            get {
                return ResourceManager.GetString("link_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string link_goto_mt {
            get {
                return ResourceManager.GetString("link_goto_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string mt_approaches_cars_report_home {
            get {
                return ResourceManager.GetString("mt_approaches_cars_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузами в адрес АМКР на подходах..
        /// </summary>
        public static string mt_approaches_cars_report_title {
            get {
                return ResourceManager.GetString("mt_approaches_cars_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string mt_approaches_sostsv_report_home {
            get {
                return ResourceManager.GetString("mt_approaches_sostsv_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы с грузами в адрес АМКР на подходах..
        /// </summary>
        public static string mt_approaches_sostsv_report_title {
            get {
                return ResourceManager.GetString("mt_approaches_sostsv_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны.
        /// </summary>
        public static string mt_arrival_cars_report_home {
            get {
                return ResourceManager.GetString("mt_arrival_cars_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны с грузополучателем АМКР.
        /// </summary>
        public static string mt_arrival_cars_report_title {
            get {
                return ResourceManager.GetString("mt_arrival_cars_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы.
        /// </summary>
        public static string mt_arrival_sostsv_report_home {
            get {
                return ResourceManager.GetString("mt_arrival_sostsv_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составы на УЗ Кривого Рога.
        /// </summary>
        public static string mt_arrival_sostsv_report_title {
            get {
                return ResourceManager.GetString("mt_arrival_sostsv_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string mt_link_all {
            get {
                return ResourceManager.GetString("mt_link_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АМКР.
        /// </summary>
        public static string mt_link_amkr {
            get {
                return ResourceManager.GetString("mt_link_amkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АМКР принятые.
        /// </summary>
        public static string mt_link_amkr_arival {
            get {
                return ResourceManager.GetString("mt_link_amkr_arival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АМКР не принятые.
        /// </summary>
        public static string mt_link_amkr_not_arival {
            get {
                return ResourceManager.GetString("mt_link_amkr_not_arival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыл на АМКР.
        /// </summary>
        public static string mt_report_field_arrival {
            get {
                return ResourceManager.GetString("mt_report_field_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз(код).
        /// </summary>
        public static string mt_report_field_cargo_code {
            get {
                return ResourceManager.GetString("mt_report_field_cargo_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род груза.
        /// </summary>
        public static string mt_report_field_cargo_type {
            get {
                return ResourceManager.GetString("mt_report_field_cargo_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка закрыта.
        /// </summary>
        public static string mt_report_field_close {
            get {
                return ResourceManager.GetString("mt_report_field_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код и станция положения.
        /// </summary>
        public static string mt_report_field_code_station_current {
            get {
                return ResourceManager.GetString("mt_report_field_code_station_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код и станция отправления.
        /// </summary>
        public static string mt_report_field_code_station_from {
            get {
                return ResourceManager.GetString("mt_report_field_code_station_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код и станция прибытия.
        /// </summary>
        public static string mt_report_field_code_station_on {
            get {
                return ResourceManager.GetString("mt_report_field_code_station_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция дислокации.
        /// </summary>
        public static string mt_report_field_code_station_сurrent {
            get {
                return ResourceManager.GetString("mt_report_field_code_station_сurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузополучатель.
        /// </summary>
        public static string mt_report_field_consignee {
            get {
                return ResourceManager.GetString("mt_report_field_consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. вагонов (шт.).
        /// </summary>
        public static string mt_report_field_count_wag {
            get {
                return ResourceManager.GetString("mt_report_field_count_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        public static string mt_report_field_country {
            get {
                return ResourceManager.GetString("mt_report_field_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол вагонов (кол. АМКР).
        /// </summary>
        public static string mt_report_field_countvag_countamkr {
            get {
                return ResourceManager.GetString("mt_report_field_countvag_countamkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка создана.
        /// </summary>
        public static string mt_report_field_create {
            get {
                return ResourceManager.GetString("mt_report_field_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата принятия на АМКР.
        /// </summary>
        public static string mt_report_field_data_arrival {
            get {
                return ResourceManager.GetString("mt_report_field_data_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принял.
        /// </summary>
        public static string mt_report_field_data_user_name {
            get {
                return ResourceManager.GetString("mt_report_field_data_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата прибытия на станцию.
        /// </summary>
        public static string mt_report_field_date_location {
            get {
                return ResourceManager.GetString("mt_report_field_date_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата операции.
        /// </summary>
        public static string mt_report_field_date_operation {
            get {
                return ResourceManager.GetString("mt_report_field_date_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Док. принятия на АМКР.
        /// </summary>
        public static string mt_report_field_doc_arrival {
            get {
                return ResourceManager.GetString("mt_report_field_doc_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код прибытия состава.
        /// </summary>
        public static string mt_report_field_idarrival {
            get {
                return ResourceManager.GetString("mt_report_field_idarrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер состава.
        /// </summary>
        public static string mt_report_field_index {
            get {
                return ResourceManager.GetString("mt_report_field_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Натурка.
        /// </summary>
        public static string mt_report_field_natur {
            get {
                return ResourceManager.GetString("mt_report_field_natur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №п.п..
        /// </summary>
        public static string mt_report_field_npp {
            get {
                return ResourceManager.GetString("mt_report_field_npp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № поезда.
        /// </summary>
        public static string mt_report_field_num_train {
            get {
                return ResourceManager.GetString("mt_report_field_num_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № вагона.
        /// </summary>
        public static string mt_report_field_num_wag {
            get {
                return ResourceManager.GetString("mt_report_field_num_wag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип операции.
        /// </summary>
        public static string mt_report_field_operation {
            get {
                return ResourceManager.GetString("mt_report_field_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        public static string mt_report_field_owner {
            get {
                return ResourceManager.GetString("mt_report_field_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примерное время прибытия в пункт назначения.
        /// </summary>
        public static string mt_report_field_time_arrival {
            get {
                return ResourceManager.GetString("mt_report_field_time_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TXT-файл (МТ).
        /// </summary>
        public static string mt_report_field_txt_file {
            get {
                return ResourceManager.GetString("mt_report_field_txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес(т.).
        /// </summary>
        public static string mt_report_field_weight {
            get {
                return ResourceManager.GetString("mt_report_field_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML-файл (МТ).
        /// </summary>
        public static string mt_report_field_xml_file {
            get {
                return ResourceManager.GetString("mt_report_field_xml_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет.
        /// </summary>
        public static string mt_report_home {
            get {
                return ResourceManager.GetString("mt_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Направление.
        /// </summary>
        public static string mt_report_route {
            get {
                return ResourceManager.GetString("mt_report_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны, отсутствующие в списке МТ, но принятые на АМКР.
        /// </summary>
        public static string mt_report_title_cars_arrival_not_mt {
            get {
                return ResourceManager.GetString("mt_report_title_cars_arrival_not_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны из списка МТ не принятые на АМКР.
        /// </summary>
        public static string mt_report_title_cars_not_arrival {
            get {
                return ResourceManager.GetString("mt_report_title_cars_not_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Массовые грузы.
        /// </summary>
        public static string mt_report_title_group_mass {
            get {
                return ResourceManager.GetString("mt_report_title_group_mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопределенные грузы.
        /// </summary>
        public static string mt_report_title_group_not {
            get {
                return ResourceManager.GetString("mt_report_title_group_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одиночные грузы.
        /// </summary>
        public static string mt_report_title_group_single {
            get {
                return ResourceManager.GetString("mt_report_title_group_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТСП.
        /// </summary>
        public static string tsp {
            get {
                return ResourceManager.GetString("tsp", resourceCulture);
            }
        }
    }
}
