//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RailWay.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RWResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RWResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_RailWay.App_LocalResources.RWResource", typeof(RWResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Четная.
        /// </summary>
        public static string even {
            get {
                return ResourceManager.GetString("even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация, полученная по данным предоставленным информационной системой RailWay. Информация о перемещении подвижного состава на территории АМКР..
        /// </summary>
        public static string index_description {
            get {
                return ResourceManager.GetString("index_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RailWay.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из системы КИС по прибытию.
        /// </summary>
        public static string kis_input {
            get {
                return ResourceManager.GetString("kis_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из системы КИС по отправке.
        /// </summary>
        public static string kis_output {
            get {
                return ResourceManager.GetString("kis_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узлы прибытия и отправки.
        /// </summary>
        public static string link_rw_station_nodes_control {
            get {
                return ResourceManager.GetString("link_rw_station_nodes_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нечетная.
        /// </summary>
        public static string odd {
            get {
                return ResourceManager.GetString("odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Между системой Railway.
        /// </summary>
        public static string railway {
            get {
                return ResourceManager.GetString("railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из системы RailWay в буфер.
        /// </summary>
        public static string railway_buffer {
            get {
                return ResourceManager.GetString("railway_buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название узла.
        /// </summary>
        public static string rw_field_nodes {
            get {
                return ResourceManager.GetString("rw_field_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторона.
        /// </summary>
        public static string rw_side_station_from {
            get {
                return ResourceManager.GetString("rw_side_station_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторона.
        /// </summary>
        public static string rw_side_station_on {
            get {
                return ResourceManager.GetString("rw_side_station_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция отправления.
        /// </summary>
        public static string rw_station_from_label {
            get {
                return ResourceManager.GetString("rw_station_from_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция прибытия.
        /// </summary>
        public static string rw_station_on {
            get {
                return ResourceManager.GetString("rw_station_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список.
        /// </summary>
        public static string rw_stations_nodes_report_home {
            get {
                return ResourceManager.GetString("rw_stations_nodes_report_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список узлов прибытия и отправки между станциями..
        /// </summary>
        public static string rw_stations_nodes_report_title {
            get {
                return ResourceManager.GetString("rw_stations_nodes_report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие.
        /// </summary>
        public static string rw_tab_title_arrival {
            get {
                return ResourceManager.GetString("rw_tab_title_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка.
        /// </summary>
        public static string rw_tab_title_sending {
            get {
                return ResourceManager.GetString("rw_tab_title_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип отправления.
        /// </summary>
        public static string rw_transfer_type {
            get {
                return ResourceManager.GetString("rw_transfer_type", resourceCulture);
            }
        }
    }
}
